permalink: /:title 
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
auto: true
pygments: true
title : zen coding
tagline: Site Tagline
author :
  name : Senthil Gopal
  email : senthil777@gmail.com
  github : senthil777
  twitter : sengopal
  feedburner : zenhacking

production_url : http://sengopal.github.com