= Ten steps to remember for Responsive Web Design
Senthilkumar Gopal
2015-07-28
:jbake-type: post
:jbake-tags: frontend
:jbake-status: published
:summary: Tips and steps used for front and responsive web development. this post contains a concise list of tools and tasks that were used for web application development.

Recently, I had to work on a frontend application and as part the learning excercise started making notes and also a presentation that i did for few team members.This is not an exhaustive list rather an opinionated front end webstack. We already have a simple backend REST service and we are developing an internal tool for reading database values and corrugated data for analysis. The typical internal tools use JSTL and boilerplate JSP code and we used this opportunity to test out some new technologies.

== Responsive Web Design ==
Starting with the first coining of the term “Responsive web design” in 2010, RWD has gone from strength to strength as a strong design approach for enabling easier access to web pages in a variety of devices. With a rapid shift in landscape from simple web browsers to rapidly growing list of devices, such as tablets, mobile phones, game controllers to name a few, RWD helps web designers create a flexible but optimized version of the pages best suited for 

Our basic design for the web always centers around a desktop oriented approach and with multiple devices beginning to overrun desktop usage, responsive design forms a strong and simpler means of reaching users with optimal design custom fit for the device in question. Responsive design takes the moral higher ground of creating a connected experience across devices rather than having totally different designs for each and every device.

RWD as an implementation is nothing new and has been possible since CSS 2.1. This presentation goes through how RWD has evolved since then, RWD versus the native app, good and bad usage with few code samples, a simple implementation and next steps.

=== Developmental tasks ===
1. Compile everything
2. Code linting
3. Running unit tests
4. Generate images as sprites
5. Minify and concatenate
6. Test HTTP Server

=== Development needs ===

1. Fast CSS protyping (preferably bootstrap)
2. livereload
3. watch compile
4. SASS source maps
5. remove unwanted css
6. Simple HTTP server

=== Tools Used ===
1. *Codekit* 
    - Watch changes to Sass/Less/Stylus and autocompile to CSS
    - Watch changes to CoffeeScript and autocompile to Javascript
    - LiveReload of browsers
    - JS and CSS Linting for errors
2. *Yeoman* - Scaffolding for the initial set of files
3. *Grunt* - Build, preview and test with Grunt
4. *Bower* - Manage dependencies and versions

=== Grunt ===
Grunt does these following steps

a. Linting
b. Compiling
c. Minification
d. Testing
e. Conversion
f. Documentation
g. Deployment

Some of the Grunt tasks commonly used were

1. `grunt-responsive-images`
2. `grunt-contrib-imageoptim`
3. `grunt-concurrent`
4. `grunt-newer`
5. `grunt-uncss`
6. `gruntsync`

=== Bower ===
Commonly used bower commands are

1. `bower search`
2. `bower search angular`
3. `bower install`
4. `bower list`

=== Yeoman ===
The scaffolding that we used for the application are created using bootstrap - `npm install generator-bootstrap -g` and we would be installing the dependencies such as `yo bootstrap`, `yo express-angular` and also `yo chrome-extension`

=== HandlebarJS ===
We have taken care of CSS and the JS components. However, the templating has many options such as Jade and HAML. However, given the timelines and the structure required we choose http://handlebarsjs.com/[HandlebarJS]. Some of the helpful links are 

1. http://handlebarsjs.com/block_helpers.html[Block Helpers]
2. http://www.slideshare.net/MindfireSolutions/introduction-to-javascript-templating-using-handlebarsjs[Slideshare]
3. http://berzniz.com/post/24743062344/handling-handlebars-js-like-a-pro[Precompiling]