= Using Netflix Hystrix for Resiliency
Senthilkumar Gopal
2015-02-28
:jbake-type: post
:jbake-tags: hystrix
:jbake-slug: using-netflix-hystrix
:jbake-status: draft

Ever since the term `services` and recently `microservices` came into usage, we have been migrating the monolithic APIs into simple and single-function microservices. However, it does come with the cost of ensuring consistent response times and resiliency in times of unavailability of certain dependencies. For example, a monlithic web application, performs a retry for every call and potentially resilient to some extent as they can recover when certain dependencies such as databases or other services are unavailable without *any additional overhead*. However for a microservice which orchestrates a bunch of dependencies each of the invocation is costly and if it is a failure reduces good user experience and also performs load stress on a system attempting to recover from failure.

"Resilience is the ability of the network to provide and maintain an acceptable level of service in the face of various faults and challenges to normal operation."
-- http://wiki.ittc.ku.edu/resilinets_wiki/index.php/Definitions#Resilience[Wikipedia]

_Explain an example of how system should be resiliency_

== What is Circuit Breaker Pattern

"The basic idea behind the circuit breaker is very simple. You wrap a protected function call in a circuit breaker object, which monitors for failures. Once the failures reach a certain threshold, the circuit breaker trips, and all further calls to the circuit breaker return with an error, without the protected call being made at all. Usually you'll also want some kind of monitor alert if the circuit breaker trips."
-- http://martinfowler.com/bliki/CircuitBreaker.html[Martin Fowler]



=== Simple Resiliency system - Circuit Breaker Design pattern
Auto mark down, Bot check, monitoring, 

Older mechanism of Mark up (close CB) - using bots
	issues
		slow, erratic, does not have ongoing telemetry, marks back up and waits for it to go down
		not embedded within system, but external

=== Disadvantages


=== Ideal circuit breaker 

Circuit Breaker + Recovery = Resiliency

Recovery time crucial for the underlying resource to recover. 
Real scenario
Network switch off for one of the COLOs, readhost replica not available, traffic routed to the other one, but latency occurred and connection stacking happened, not allowing resource to come back up.

== Netflix Hystrix


=== How to use?


=== Out of the box components
Monitoring
runtime config management


=== Usage in eBay
Authentication adaptor
hystrix.command.r1raptorIAFGetTokenByRefCommand.execution.isolation.thread.timeoutInMilliseconds


=== References
* http://techblog.netflix.com/2012/11/hystrix.html
* https://github.com/Netflix/Hystrix/wiki
* http://techblog.netflix.com/2011/12/making-netflix-api-more-resilient.html
* http://doc.akka.io/docs/akka/snapshot/common/circuitbreaker.html