= About Me
Senthilkumar Gopal
2015-08-10
:jbake-type: page
:jbake-tags: about
:jbake-status: published

I am Senthilkumar Gopal, a developer working at http://www.ebay.com"[eBay]. After graduating with a major in Engineering, started with Java based web technologies and coding since then. I am on https://twitter.com/sengopal[Twitter], http://github.com/sengopal[Github] and http://www.linkedin.com/in/senthilkumargopal[LinkedIn].

I gained most of my technical know-how by self learning, starting from 2005, when I first learnt to program in Java. In 2006, I started developing backend services with a bit of Javascript and CSS. In 2010 i joined eBay Inc., and my foray into full fledged product development began from there. I now develop extensively on server based development, primarily using Java and client intensive applications with Javascript and CSS, with major focus on responsive web design and better development workflows.

Recently I moved to the authentication systems team and working extensively on backend architecture, creating the new services authentication protocols, database systems and more. As part of this new position, i have started learning about OAuth 2.0, SAML assertions etc.,

I am not a very enthusiastic blogger, as i write more code than blog posts. However, i enjoy writing with the sense of sharing my thoughts and findings. There are no comments sections for these blog posts but you are welcome to discuss about anything on this blog on Hacker News or contact me on http://twitter.com/sengopal[Twitter] or you can also email at mailto:senthil777@gmail.com[me]
