= Résumé
Senthilkumar Gopal
2013-10-17
:jbake-type: page
:jbake-tags: resume
:jbake-status: published


:toc: right

== Summary


== Professional Experience

=== http://www.ebay.com[eBay Inc]

*Member of Technical Staff I*

_Jan 2010 - present_

===== IAF and Authentication Systems
* Designing and developing the next generation token mechanism for authentication of internal and external applications

===== Vendor Integration Gateway Developer and Evangelist
* Designed and implemented gateway applications for vendor integrations such as Zoot, Jumio, Telesign, Targus etc.,
* Designed and developed the end-to-end integration with Seller Registration flow
* Async Microservices architecture pattern for vendor communication, profile evaluation and PayPal integration

===== Web Application Developer
* Redesigned the FYP application to handle heavy traffic to ensure site availability during global password reset
* Design and develop product changes, analyze IO calls and optimize either by data structures or query optimization
* Iterative UX changes to ensure responsiveness of the web pages, page speed optimization and site monitoring

==== Verification Platform 3.0 - self-driven initiative
* Designed and developed a full fledged verification dashboard which helps analyze a user’s verification history
* designed and developed an extensible batch framework for monitoring critical site metrics
* Designed and developed Verification base framework for rapid application creation using Spring MVC
* TaaS - designed and developed a Texting as a Service for multiple clients with consumer based tracking & monitoring

==== Document Verification 
* Designed the architecture for image upload, async validation, security protocols for vendor comm. and data storage
* Developing POCs for multi-device usage using HTML5 APIs and polyfills for upload using getUserMedia API etc.,

==== Re-Architecture of Known Good Remedy
* Designed and developed with modern web stack using Spring MVC, Git and Cloud deployments (Raptor)
* complete documentation of the existing functionality, design and development of the backend SOA services

==== Global Seller Registration
* First ever PCI compliant secure Raptor infrastructure pool
* Designed, developed and lead the end to end development of the application and backend SOA services.
* Setup a secure pool in Raptor working closely with Network & Information security, Operations, Infrastructure etc.,

==== Seller Registration - Migration to Services
* Designed/developed a simplified two-tiered Service structure to enable multiple clients perform verification flows

==== Seller Upgrade Limits for US [as contractor for eBay]
* Designed and developed a new Orchestration framework which combines multiple verification flows to provide a streamlined experience and was achieved using URL redirection and with internal state persistence.

* Established security standards for vendor communications for KBA within the upgrade limits application

=== http://www.mphasis.com[Mphasis FinSolutions]

*Senior Software Engineer*

_Jun 2008 - Jan 2010_

==== Web Asset Tracker
* Designed/developed the application based on in-house eBIZ Framework, data modeling and using Web 2.0(Accordions, Lightbox), Export to Excel and PDF generation.

==== eBiz Business Platform (v3.6) 
* Developed functionalities like Navigation using Google Maps, Tag libraries for Calendar, ICS Calendar generation etc.
* Offshore Lead for evaluating multiple Javascript libraries and incorporating jQuery into the platform

=== http://www.infosys.com[Infosys Technologies]

*Software Engineer 2*

_Nov 2005 - Jun 2008_

==== Valuations Information Management System and Credit Risk Management System
* Developed the Quartz job scheduling system, PDF generation through PD4ML and Hibernate Query tuning
* Offshore Team Lead and SME for the legacy VB 6.0 system and developed POCs for word document generation

== Academics
* Bachelor of Engineering (2001-2005) from Sathyabama Engineering College with 90%
* S.S.L.C. (Matriculation) with 86% and Higher Secondary (+2) with 95%
* Sun Certified Web Component Developer 5 and Sun Certified Java Programmer
* Coursera - Programming Mobile Applications for Android Handheld Systems with distinction

== Awards and Recognition
* Received acclaim and executive appreciation for leading the Global password reset (Q3 2014) project changes and monitoring
* Received the Spot Award in Q2 2014 for investigating dips in completion and resilient design structure
* Awarded the Exceptional Critical Talent Award in 2014 for overall Verification platform contributions
* Awarded the Going the Extra Mile Award for 2014 
* Awarded the Shining Star Spot Award in Q3 2013 for creating the first ever Raptor PCI compliant secure pool
* Awarded the Business Innovation Award in 2012 for evangelizing the Vendor Integration Gateway in Technovate
* Awarded the Cosmic Kudos Spot Award in Q1 2012 for developing the Vendor Integration Gateway
* Won the coding Hackathon (Accelerate 2011) for developing a social data based application for eBay - Social Nod
* Awarded the Blue Moon Spot award in Q4 2011 for re-architecturing the German Seller Registration
* Awarded the Blue Moon Spot award in Q2 2011 for creating the Verification Orchestration framework for Strong ID remedy
* Awarded the Blue Moon Spot award in Q3 2010 for Seller Upgrade Limits
* Awarded the Productivity Excellence Award in 2010 for contributions to Fraud and Risk platform
* Awarded Developer of the Month for the critical work done for eBiz Platform - Javascript Framework Evaluation

== Skills

[options=""]
|===
|Java Core 					| J2EE architecture and design, Java, Design Patterns
|Open source frameworks		| Spring MVC, Spring Batch, Handlebar JS
|Java Libraries				| Junit, Struts, Hibernate, Quartz, WordML,PD4ML, Velocity, JAXB, JSTL
|Web Technologies			| Ajax, SOA, REST, jQuery, CSS, SASS
|===

== Contributions
* Conducted sessions on Responsive Web Design, Secure PCI pool, Git & Github, Spring Batch
* Internal blog posts on the Seller Registration end to end architecture design and development
