= Résumé
Senthilkumar Gopal
2015-03-22
:jbake-type: page
:jbake-tags: resume
:jbake-status: published

== Summary
I am involved with Web application design and development with primary expertise in J2EE and other Java based applications. My work heavily involves design, security, performance and availability. I also have worked with frontend technologies for single page applications and client side intensive webapps.

== Professional Experience

=== http://www.ebay.com[eBay Inc]

*Member of Technical Staff I*

_Jan 2010 - present_

===== IAF and Authentication Systems
I am responsible for designing and developing the next generation token mechanism for authentication of internal and external applications

===== Vendor Integration Gateway Developer and Evangelist
I design the gateway applications for external vendor integrations for risk evaluation and verification systems, their end-to-end integration with user verification flows using Async Microservices architecture patterns. I design the architecture for communication, validation, security protocols for vendor communications and data storage along with completing the development for proof-of-concepts for multi-device usage.

===== Web Application Developer
I redesign web applications to handle high traffic to increase site availability. I am also involved in design and development of product changes, analyzing IO calls and optimization. As personal side projects, I also designed and implemented

* a full fledged verification dashboard which helps analyze a user’s verification history
* an extensible batch framework for monitoring critical site metrics
* a base framework for rapid application creation using Spring MVC
* (TaaS) Texting as a Service with consumer based tracking & monitoring

=== http://www.mphasis.com[Mphasis FinSolutions]

*Senior Software Engineer*

_Jun 2008 - Jan 2010_

I was responsible for esign and development for applications based on in-house eBIZ Framework, data modeling and using Web 2.0 (Accordions, Lightbox) components, functionalities such as Export to Excel and PDF generation. I also added capabilities such as  Navigation using Google Maps, Tag libraries for Calendar, ICS Calendar generation etc.

=== http://www.infosys.com[Infosys Technologies]

*Software Engineer 2*

_Nov 2005 - Jun 2008_

I worked on java based backend systems and developed batch jobs using Quartz scheduling system, PDF generation through PD4ML and worked on Hibernate Query tuning.

== Academics
* Bachelor of Engineering (2001-2005) from Sathyabama Engineering College with 90%
* S.S.L.C. (Matriculation) with 86% and Higher Secondary (+2) with 95%
* Sun Certified Web Component Developer 5 and Sun Certified Java Programmer
* Coursera - Programming Mobile Applications for Android Handheld Systems with distinction

== Awards and Recognition
I have recieved multiple internal awards for work related to application architecture, redesign of verification platform, Vendor integration gateway and other contributions.

== Skills

[cols="1,2", options=""]
|===
|Java Core 					| J2EE architecture and design, Java, Design Patterns
|Open source frameworks		| Spring MVC, Spring Batch, Handlebar JS
|Java Libraries				| Junit, Struts, Hibernate, Quartz, WordML,PD4ML, Velocity, JAXB, JSTL
|Web Technologies			| Ajax, SOA, REST, jQuery, CSS, SASS
|===

== Contributions
* Conducted sessions on Responsive Web Design, Secure PCI pool, Git & Github, Spring Batch
* Internal blog posts on the Seller Registration end to end architecture design and development
